export const bardSpells: string[][] = [
    [
        "Blade ward",
        "Dancing lights",
        "Friends",
        "Light",
        "Mage hand",
        "Mending",
        "Message",
        "Minor illusion",
        "Prestidigitation",
        "Thunderclap",
        "True strike",
        "Vicious mockery"
    ],
    [
        "Animal friendship",
        "Bane",
        "Charm person",
        "Comprehend languages",
        "Cure wounds",
        "Detect magic",
        "Disguise self",
        "Dissonant whispers",
        "Earth tremor",
        "Faerie fire",
        "Feather fall",
        "Healing word",
        "Heroism",
        "Identify",
        "Illusory script",
        "Longstrider",
        "Silent image",
        "Sleep",
        "Speak with animals",
        "Tasha's hideous laughter",
        "Thunderwave",
        "Unseen servant"
    ]
];

export const clericSpells: string[][] = [
    [
        "Guidance",
        "Light",
        "Mending",
        "Resistance",
        "Sacred flame",
        "Spare the dying",
        "Thaumaturgy",
        "Toll the dead",
        "Word of radiance"
    ],
    [
        "Bane",
        "Bless",
        "Ceremony",
        "Command",
        "Create or destroy water",
        "Cure wounds",
        "Detect evil and good",
        "Detect magic",
        "Detect poison and disease",
        "Guiding bolt",
        "Healing word",
        "Inflict wounds",
        "Protection from evil and good",
        "Purify food and drink",
        "Sanctuary",
        "Shield of faith"
    ]
];

export const paladinSpells: string[][] = [
    [],
    [
        "Bless",
        "Command",
        "Compelled duel",
        "Cure wounds",
        "Detect evil and good",
        "Detect magic",
        "Detect poison and disease",
        "Divine favor",
        "Heroism",
        "Protection from evil and good",
        "Purify food and drink",
        "Searing smite",
        "Shield of faith",
        "Thunderous smite",
        "Wrathful smite"
    ]
];

export const rangerSpells: string[][] = [
    [],
    [
        "Alarm",
        "Animal friendship",
        "Cure wounds",
        "Detect magic",
        "Detect poison and disease",
        "Ensnaring strike",
        "Fog cloud",
        "Goodberry",
        "Hail of thorns",
        "Hunter's mark",
        "Jump",
        "Longstrider",
        "Speak with animals"
    ]
];

export const druidSpells: string[][] = [
    [
        "Control flames",
        "Create bonfire",
        "Druidcraft",
        "Frostbite",
        "Guidance",
        "Gust",
        "Infestation",
        "Magic stone",
        "Mending",
        "Mold earth",
        "Poison spray",
        "Primal savagery",
        "Produce flame",
        "Resistance",
        "Shape water",
        "Shillelagh",
        "Thorn whip",
        "Thunderclap"
    ],
    [
        "Absorb elements",
        "Animal friendship",
        "Beast bond",
        "Charm person",
        "Create or destroy water",
        "Cure wounds",
        "Detect magic",
        "Detect poison and disease",
        "Earth tremor",
        "Entangle",
        "Faerie fire",
        "Fog cloud",
        "Goodberry",
        "Healing word",
        "Ice knife",
        "Jump",
        "Longstrider",
        "Purify food and drink",
        "Snare",
        "Speak with animals",
        "Thunderwave"
    ]
];

export const sorcererSpells: string[][] = [
    [
        "Acid splash",
        "Blade ward",
        "Booming blade",
        "Chill touch",
        "Control flames",
        "Create bonfire",
        "Dancing lights",
        "Fire bolt",
        "Friends",
        "Frostbite",
        "Green flame blade",
        "Gust",
        "Infestation",
        "Light",
        "Lightning lure",
        "Mage hand",
        "Mending",
        "Message",
        "Minor illusion",
        "Mold earth",
        "Poison spray",
        "Prestidigitation",
        "Ray of frost",
        "Shape water",
        "Shocking grasp",
        "Sword burst",
        "Thunderclap",
        "True strike"
    ],
    [
        "Absorb elements",
        "Burning hands",
        "Catapult",
        "Chaos bolt",
        "Charm person",
        "Chromatic orb",
        "Color spray",
        "Comprehend languages",
        "Detect magic",
        "Disguise self",
        "Earth tremor",
        "Expeditious retreat",
        "False life",
        "Feather fall",
        "Fog cloud",
        "Ice knife",
        "Jump",
        "Mage armor",
        "Magic missile",
        "Ray of sickness",
        "Shield",
        "Silent image",
        "Sleep",
        "Thunderwave",
        "Witch bolt"
    ]
];

export const warlockSpells: string[][] = [
    [
        "Blade ward",
        "Booming blade",
        "Chill touch",
        "Create bonfire",
        "Eldritch blast",
        "Friends",
        "Frostbite",
        "Green flame blade",
        "Infestation",
        "Lightning lure",
        "Mage hand",
        "Magic stone",
        "Minor illusion",
        "Poison spray",
        "Prestidigitation",
        "Sword burst",
        "Thunderclap",
        "Toll the dead",
        "True strike"
    ],
    [
        "Armor of agathys",
        "Arms of hadar",
        "Cause fear",
        "Charm person",
        "Comprehend languages",
        "Expeditious retreat",
        "Hellish rebuke",
        "Hex",
        "Illusory script",
        "Protection from evil and good",
        "Unseen servant",
        "Witch bolt"
    ]
];

export const wizardSpells: string[][] = [
    [
        "Acid splash",
        "Blade ward",
        "Booming blade",
        "Chill touch",
        "Control flames",
        "Create bonfire",
        "Dancing lights",
        "Encode thoughts",
        "Fire bolt",
        "Friends",
        "Frostbite",
        "Green flame blade",
        "Gust",
        "Infestation",
        "Light",
        "Lightning lure",
        "Mage hand",
        "Mending",
        "Message",
        "Minor illusion",
        "Mold earth",
        "Poison spray",
        "Prestidigitation",
        "Ray of frost",
        "Shape water",
        "Shocking grasp",
        "Sword burst",
        "Thunderclap",
        "Toll the dead",
        "True strike"
    ],
    [
        "Absorb elements",
        "Alarm",
        "Burning hands",
        "Catapult",
        "Cause fear",
        "Charm person",
        "Chromatic orb",
        "Color spray",
        "Comprehend languages",
        "Detect magic",
        "Disguise self",
        "Earth tremor",
        "Expeditious retreat",
        "False life",
        "Feather fall",
        "Find familiar",
        "Fog cloud",
        "Grease",
        "Ice knife",
        "Identify",
        "Illusory script",
        "Jump",
        "Longstrider",
        "Mage armor",
        "Magic missile",
        "Protection from evil and good",
        "Ray of sickness",
        "Shield",
        "Silent image",
        "Sleep",
        "Snare",
        "Tasha's hideous laughter",
        "Tenser's floating disk",
        "Thunderwave",
        "Unseen servant",
        "Witch bolt"
    ]
];

export const necromancySpells: string[][] = [
    [
        "Chill touch",
        "Spare the dying",
        "Toll the dead"
    ],
    [
        "False life",
        "Inflict wounds",
        "Ray of sickness"
    ]
];

export const level1Spells: string[] = [
    "Alarm",
    "Animal friendship",
    "Bane",
    "Bless",
    "Burning hands",
    "Charm person",
    "Color spray",
    "Command",
    "Comprehend languages",
    "Create or destroy water",
    "Cure wounds",
    "Detect evil and good",
    "Detect magic",
    "Detect poison and disease",
    "Disguise self",
    "Divine favor",
    "Entangle",
    "Expeditious retreat",
    "Faerie fire",
    "False life",
    "Feather fall",
    "Find familiar",
    "Floating disk",
    "Fog cloud",
    "Goodberry",
    "Grease",
    "Guiding bolt",
    "Healing word",
    "Hellish rebuke",
    "Heroism",
    "Hideous laughter",
    "Hunter's mark",
    "Identify",
    "Illusory script",
    "Inflict wounds",
    "Jump",
    "Longstrider",
    "Mage armor",
    "Magic missile",
    "Protection from evil and good",
    "Purify food and drink",
    "Sanctuary",
    "Shield",
    "Shield of faith",
    "Silent image",
    "Sleep",
    "Speak with animals",
    "Thunderwave",
    "Unseen servant"
];

export const level2Spells: string[] = [
    "Acid arrow",
    "Aid",
    "Alter self",
    "Animal messenger",
    "Arcane lock",
    "Arcanist's magic aura",
    "Augury",
    "Barkskin",
    "Blindness deafness",
    "Blur",
    "Branding smite",
    "Calm emotions",
    "Continual flame",
    "Darkness",
    "Darkvision",
    "Detect thoughts",
    "Enhance ability",
    "Enlarge reduce",
    "Enthrall",
    "Find steed",
    "Find traps",
    "Flame blade",
    "Flaming sphere",
    "Gentle repose",
    "Gust of wind",
    "Heat metal",
    "Hold person",
    "Invisibility",
    "Knock",
    "Lesser restoration",
    "Levitate",
    "Locate animals or plants",
    "Locate object",
    "Magic mouth",
    "Magic weapon",
    "Mirror image",
    "Misty step",
    "Moonbeam",
    "Pass without trace",
    "Prayer of healing",
    "Protection from poison",
    "Ray of enfeeblement",
    "Rope trick",
    "Scorching ray",
    "See invisibility",
    "Shatter",
    "Silence",
    "Spider climb",
    "Spike growth",
    "Spiritual weapon",
    "Suggestion",
    "Warding bond",
    "Web",
    "Zone of truth"
];

export const level3Spells: string[] = [
    "Animate dead",
    "Beacon of hope",
    "Bestow curse",
    "Blink",
    "Call lightning",
    "Clairvoyance",
    "Conjure animals",
    "Counterspell",
    "Create food and water",
    "Daylight",
    "Dispel magic",
    "Fear",
    "Fireball",
    "Fly",
    "Gaseous form",
    "Glyph of warding",
    "Haste",
    "Hypnotic pattern",
    "Lightning bolt",
    "Magic circle",
    "Major image",
    "Mass healing word",
    "Meld into stone",
    "Nondetection",
    "Phantom steed",
    "Plant growth",
    "Protection from energy",
    "Remove curse",
    "Revivify",
    "Sending",
    "Sleet storm",
    "Slow",
    "Speak with dead",
    "Speak with plants",
    "Spirit guardians",
    "Stinking cloud",
    "Tiny hut",
    "Tongues",
    "Vampiric touch",
    "Water breathing",
    "Water walk",
    "Wind wall"
];